Cloud = ['planets/Cloud_normal.png']
Habit = ['planets/Habit_1.png','planets/Habit_2.png','planets/Habit_3.png','planets/Habit_4.png','planets/Habit_5.png']
Ice = ['planets/Ice_low.png','planets/Ice_minimum.png','planets/Ice_average.png','planets/Ice_severe.png','planets/Ice_extreme.png']
nbio_water = ['planets/nbio_water_1.png','planets/nbio_water_2.png','planets/nbio_water_3.png']
nbio = ['planets/nbio_1.png']
Gas = ['planets/Gas_1.png']
Star = ['planets/star_dwarf.png','planets/star_average.png','planets/star_giant.png']
Solar = ['planets/Solar.png']
#[1,3,4,5]
PlanetList = [Cloud,Habit,Ice,nbio_water,nbio,Gas,Star]
